# Generated by Django 5.0.6 on 2024-05-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='media')),
            ],
        ),
    ]
